---
title: "Subcatchment 78"
author: "Lauren Skube"
date: "1/30/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) #For data wrangling
library(here)
library(kableExtra) # for tables
library(gganimate) # for creating gif
```

```{r}
#read in data
subcatch_78runoff <- read.csv(here("LID_Graphs", "subcatchment78_LID_runoff.csv"))
wailupe_greenroof_top5 <- read.csv(here("LID_Graphs", "wailupe_greenroof_top5.csv"))
```


```{r}
#Create graph for subcatchment 78 runoff 

cbp2 <- c("#D55E00","#009E73", "#000000")

runoff_78 <- ggplot(subcatch_78runoff, aes(x=time, y = runoff_cfs, color = lid_type)) + 
  geom_line(aes(color=lid_type), size= 1.5)+
  theme_classic()+
  labs(x="Time (hours)", y="Discharge (cfs)")+
  scale_y_continuous(limits= c(0,35), breaks= seq(0,30, by= 5),expand= c(0,0))+
  scale_x_continuous(limits= c(4,12), breaks= seq(0,12, by= 1),expand= c(0,0))+
  theme(legend.title = element_blank())+
  theme(legend.position="bottom") +
  scale_colour_manual(labels = c("Green Roof + Permeable Pavement", "Green Roof", "No LID"), values= cbp2) +
  theme(text=element_text(color="black"),axis.text=element_text(color="black")) +
  theme(text = element_text(size =26))

runoff_78

ggsave("lid_runoff_78.png", runoff_78, width = 16, height = 10, units = "in" )

## animated plot

runoff_78_animate <- ggplot(subcatch_78runoff, aes(x=time, y = runoff_cfs, color = lid_type)) + 
  geom_line(aes(color=lid_type), size= 1.5)+
  theme_classic()+
  labs(x="Time (hours)", y="Discharge (cfs)")+
  scale_y_continuous(limits= c(0,35), breaks= seq(0,30, by= 5),expand= c(0,0))+
  scale_x_continuous(limits= c(4,12), breaks= seq(0,12, by= 1),expand= c(0,0))+
  theme(legend.title = element_blank())+
  theme(legend.position="bottom") +
  scale_colour_manual(labels = c("Green Roof + Permeable Pavement", "Green Roof", "No LID"), values= cbp2) +
  theme(text=element_text(color="black"),axis.text=element_text(color="black")) +
  theme(text = element_text(size =26)) +
    transition_reveal(time)

runoff_78_animate

# animate in a two step process:
 # animate(runoff_78_animate, height = 900, width =1000, renderer = gifski_renderer(loop = FALSE), bg = 'transparent')
  # anim_save("runoff_78_animate.gif")  
```

```{r}
# graph green roof scenarios for top 5 runoff hotspots 

cbp2 <- c("#000000","#D55E00","#009E73", 'blue')

top5 <- ggplot(wailupe_greenroof_top5, aes(x=time, y = runoff_cfs, color = perc_greenroof)) + 
  geom_line(aes(color=perc_greenroof), size= 1.25)+
  theme_classic() +
  facet_wrap(~factor(subcatchment, levels=c('Subcatchment 67','Subcatchment 68','Subcatchment 45','Subcatchment 47', 'Subcatchment 60')), scales = "free")+ # arrange by 67, 68, 45, 47, 60  
  labs(x="Time (hours)", y="Discharge (cfs)")+
  scale_y_continuous(limits= c(0,14), breaks= seq(0,14, by= 2),expand= c(0,0))+
  scale_x_continuous(limits= c(4,11), breaks= seq(4,11, by= 2),expand= c(0,0))+
  theme(panel.spacing.x = unit(10, "mm"), 
        panel.spacing.y= unit(10, "mm"),
        strip.background = element_blank()) +
  theme(legend.position="right") +
  scale_colour_manual(labels = c("0%", "20%", "30%", "50%"), values= cbp2, name = "Percent residential homes \nwith greenroofing") +
  theme(text=element_text(color="black"),axis.text=element_text(color="black")) +
  theme(text = element_text(size =28)) + 
  theme(
    legend.position = c(.98, .38),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6), 
    legend.key.size = unit(1.5, "cm"),
    legend.title=element_text(size=28)) 

top5

ggsave("top5.png", top5, width = 20, height = 10, units = "in")

```

## Wailupe Green Roofs Percentile 
```{r}
## read in each percent green roof
wailupe_greenroof_20perc <- read.csv(here("LID_Graphs", "wailupe_green_roofs_20percentresults.csv"))
wailupe_greenroof_30perc <- read.csv(here("LID_Graphs", "wailupe_green_roofs_30percentresults.csv"))
wailupe_greenroof_50perc <- read.csv(here("LID_Graphs", "wailupe_green_roofs_50percentresults.csv"))
```

```{r} 
wailupe_greenroof_20perc_table <- wailupe_greenroof_20perc %>% 
  arrange(desc(Runoff.Coefficient)) %>%  
  kable(col.names=c("Subcatchment","Total Runoff (10$^{6}$ gal)", "Peak Runoff (cfs)", "Runoff Coefficient")) %>%
  kable_styling(bootstrap_options = "striped")

wailupe_greenroof_20perc_table


wailupe_greenroof_30perc_table <- wailupe_greenroof_30perc %>% 
  arrange(desc(Runoff.Coefficient)) %>%  
  kable(col.names=c("Subcatchment","Total Runoff (10$^{6}$ gal)", "Peak Runoff (cfs)", "Runoff Coefficient")) %>%
  kable_styling(bootstrap_options = "striped")

wailupe_greenroof_30perc_table

wailupe_greenroof_50perc_table <- wailupe_greenroof_50perc %>% 
  arrange(desc(Runoff.Coefficient)) %>%  
  kable(col.names=c("Subcatchment","Total Runoff (10$^{6}$ gal)", "Peak Runoff (cfs)", "Runoff Coefficient")) %>%
  kable_styling(bootstrap_options = "striped")

wailupe_greenroof_50perc_table
```


## GI graph for publics, sub 78 runoff with no lid vs greenroof + permeable pavement 
```{r}
## black = no lid 
## blue = combined = #03989E

cp3 <- c("#03989E", "#000000")

subcatch_78runoff_nolid_comb <- subcatch_78runoff %>% 
  filter(lid_type %in% c("no_lid", "combined"))

# to export sub 78 df with just no_lid and combined greenroof and permeable pavement 
# write.csv(subcatch_78runoff_nolid_comb, "subcatch_78runoff_nolid_comb.csv")

runoff_78_nolid_comb <- ggplot(subcatch_78runoff_nolid_comb, aes(x=time, y = runoff_cfs, color = lid_type)) + 
  geom_line(aes(color=lid_type), size= 1.5)+
  theme_classic()+
  labs(x="Time (hours)", y="Discharge (cfs)")+
  scale_y_continuous(limits= c(0,32), breaks= seq(0,30, by= 10),expand= c(0,0))+
  scale_x_continuous(limits= c(4,11), breaks= seq(0,12, by= 2),expand= c(0,0))+
  theme(legend.title = element_blank())+
  theme(legend.position="bottom") +
  scale_colour_manual(labels = c("Green Roof + Permeable Pavement", "No Green Infastructure"), values= cp3) +
  theme(text=element_text(color="black"),axis.text=element_text(color="black")) +
  theme(text = element_text(size =38))

runoff_78_nolid_comb

# ggsave("runoff_78_nolid_comb.png", runoff_78_nolid_comb, width = 16, height = 10, units = "in" )

## animated plot for publics
runoff_78_nolid_comb_animate <- ggplot(subcatch_78runoff_nolid_comb, aes(x=time, y = runoff_cfs, color = lid_type)) + 
  geom_line(aes(color=lid_type), size= 1.5)+
  theme_classic()+
  labs(x="Time (hours)", y="Discharge (cfs)")+
  scale_y_continuous(limits= c(0,32), breaks= seq(0,30, by= 10),expand= c(0,0))+
  scale_x_continuous(limits= c(4,11), breaks= seq(0,12, by= 2),expand= c(0,0))+
  theme(legend.title = element_blank())+
  theme(legend.position="bottom") +
  scale_colour_manual(labels = c("Green Roof + Permeable Pavement", "No Green Infastructure"), values= cp3) +
  theme(text=element_text(color="black"),axis.text=element_text(color="black")) +
  theme(text = element_text(size=38)) +
  transition_reveal(time) +
  theme(
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
  )

runoff_78_nolid_comb_animate

# animate in a two step process:
 animate(runoff_78_nolid_comb_animate, height = 900, width =1000, renderer = gifski_renderer(loop = FALSE), bg = 'transparent')

 # anim_save("runoff_78_nolid_comb_animate.gif") 

```

